### ISSUE TITLE
Display correlationId in generated doc

### ISSUE THREAD

**Issue by M3lkior** [asyncapi/html-template#108]
#### Reason/Context
Please try answering few of those questions
- Why we need this improvement?

In my case, i'm using Kafka to do Events exchanges. I use [Request-reply](https://www.enterpriseintegrationpatterns.com/patterns/messaging/RequestReply.html) for exchange with the [CorrelationIdentifier pattern](https://www.enterpriseintegrationpatterns.com/patterns/messaging/CorrelationIdentifier.html)

- How will this change help?

My producers and consumers must see in the doc how the correlationId is generated (based on which fields in the contract) to allow filtering on correlationId for example.

- What is the motivation? 

#### Description
Please try answering few of those questions
- What changes have to be introduced?

Display informations about `CorrelationId` in `message` documentation

- Will this be a breaking change?

no
- How could it be implemented/designed?

UI proposal :

![image](https://user-images.githubusercontent.com/5501911/96564554-95700000-12c3-11eb-9d50-fb2e23297cc6.png)

Code Snippet : 

```
<div class="bg-grey-lighter rounded p-4 mt-2">
  <div class="text-sm text-grey-darker mb-2">Correlation ID<span class="border text-orange rounded text-xs ml-3 py-0 px-2">$message.header#/CLIENT_CODE $message.payload#/PRODUCT_ID</span>
    
  </div>
  <p class="text-grey-dark text-sm">This correlation ID is used for message tracing and messages correlation.
            This correlation ID is generated at runtime based on Client ID / Product ID and costing request timestamp</p>
  
</div>
```

- the CorrelationID `location` attribut is describe into the `text-sm text-grey-darker mb-2` CSS classes

**Comment by derberg** [comment]
@M3lkior lgtm but yeah, I'm not the guy that has a good design sense...they say so 😆 

@fmvilas even though I'm known for being super bad at choosing colors I think that @M3lkior proposal is pretty good. Thoughts?

**Comment by fmvilas** [comment]
Yup. Looks good to me too. Let's make sure it's hidden if no correlationId is given.

**Comment by derberg** [comment]
@M3lkior wanna give it a try?

**Comment by M3lkior** [comment]
Yeah, if the correlationId attribut is already present in the templating context; i think it could be achieve in few hours :)

**Comment by derberg** [comment]
@M3lkior template works on a AsyncAPI document that is already parsed by the AsyncAPI Parser. You have access to all the helper functions to access the contents of AsyncAPI document. 

You would only need to add correlationId sample here to thid dummy example https://github.com/asyncapi/generator/blob/master/test/docs/dummy.yml so you get a sample data to work on during template development

In the template, where message rendering is defined https://github.com/asyncapi/html-template/blob/master/partials/message.html you have access to an additional functions like `msg.correlationId()` that returns `null` in it is not there.
You can also do  `msg.correlationId().location()`,  `msg.correlationId().hasDescription()` and  `msg.correlationId().description()`

One last remark, the box with correlationId should be part of message box because at the end it is part of the message and not the channel. You can have a message that is `oneOf` and 2 different messages mentioned there can have different correlationIds, so this case has to be taken into account.

I hope that help. Let me know if ya need some help

**Comment by M3lkior** [comment]
Ok so what about this rendering ?

![image](https://user-images.githubusercontent.com/5501911/96695769-55c01b80-138a-11eb-9496-ec33c831bdbd.png)

The attached snippet : 

```
<div class="border border-grey-light bg-grey-lightest rounded p-4 mt-2">
  <div class="text-sm text-grey-darker mb-2">Correlation ID<span class="border text-orange rounded text-xs ml-3 py-0 px-2">$message.header#/CLIENT_CODE $message.payload#/PRODUCT_ID</span>
    
  </div>
  <p class="text-grey-dark text-sm">This correlation ID is used for message tracing and messages correlation.
            This correlation ID is generated at runtime based on Client ID / Product ID and costing request timestamp</p>
  
</div>
```

**Comment by derberg** [comment]
yeap, right above the payload, makes sense and still looks good

[here](https://raw.githubusercontent.com/asyncapi/tck/fb062a4bd9798ab9b277abbe109e13264326bfb8/tests/asyncapi-2.0/Operation%20Object/valid-multiple-messages.yaml) you have an example of such a channel that has multiple messages

**Comment by M3lkior** [comment]
Nice. 

I read this morning about [`Correlation Identifier` EIP pattern ](https://www.enterpriseintegrationpatterns.com/patterns/messaging/CorrelationIdentifier.html) and in a major of use case, the `CorrelationID` is define in the message headers  : 

- The requestor send a message with a `Request ID` in his message header
- The replier send back to a response topic a message with a `Correlation ID` in header

So do you think that this information can be usefull for another use case than `request-reply` EIP pattern ?

**Comment by fmvilas** [comment]
It is also very useful for distributed tracing. For instance, to understand where a whole "chain" of messages originated and what were the steps it followed during its way.

For instance:

1. REST API receives a POST /signup and it publishes a **UserSignedUp** message with a unique correlation Id.
    1. An "Email microservice" receives the message, sends a welcome email to the user, and publishes a **UserWelcomeEmailSent** message with the same correlation Id.
        1. A "Business Metrics microservice" receives the **UserWelcomeEmailSent** and increments the number of "Welcome Emails Sent" by one (or whatever other fancy stuff).
    1. A "Notifications microservice" receives the message and posts a message in Slack.

In this scenario, now suppose we have New Relic or similar installed in every microservice. New Relic would be able to tell us what has been the "trip" of that message, which would be something like this:

```
                          / ------> Email Service ------> Business Metrics Service
REST API UserSignedUp ---<
                          \ ------> Notifications Service
```

Does it make sense?

**Comment by derberg** [comment]
I would also add that it doesn't have to be header and not necessarily called `correlationId`. Sometimes it is referred to as `clientRequestId` and can be part of the payload. Have a look at example from Azure using CloudEvents as an envelope for the payload https://docs.microsoft.com/en-us/azure/event-grid/cloud-event-schema#sample-event-using-cloudevents-schema

@fmvilas this makes me think why would `correlationId` has its own unique presence in the specification. Is it because of the code generation? If in the end it is part of headers or payload, it is a kind of duplication of information. Side topic not related to this issue - can be ignored 😄

**Comment by fmvilas** [comment]
@derberg it's for semantic reasons. We already have the information in headers or payload but we don't know which field is the correlation Id. **We don't know the meaning of the data, just its structure**. We also can't add an attribute to the field definition inside headers or payload because they are pure JSON Schema objects. Or Avro, RAML, etc. in the case of payload.

**Comment by derberg** [comment]
@M3lkior I made it much easier for you to contribute this one. I did a live stream for the Hacktoberfest and worked on this issue -> https://youtu.be/k8aS_houYlY?t=1915

**Comment by derberg** [comment]
the official dummy example is now extended with examples of correlationId https://github.com/asyncapi/generator/blob/master/test/docs/dummy.yml
