### ISSUE TITLE
"Welcome first time contributors" CI step fails for first time contributors

### ISSUE THREAD

**Issue by jamescrowley** [asyncapi/html-template#14]
#### Describe the bug

When opening a PR for the first time, the build fails due to the 'welcome first time contributors' step. 

#### How to Reproduce

See https://github.com/asyncapi/html-template/runs/619246280 . I'm guessing something to do with the API permissions to trigger the ``[error]Resource not accessible by integration`` error

#### Expected behavior

This shouldn't fail.

**Comment by derberg** [comment]
Unfortunately we cannot do to much here 😞  It fails only once with first interaction because GitHub Actions do not support PRs from forks the same way as from the upstream branch.

I described this limitation here: https://dev.to/derberg/github-actions-when-fascination-turns-into-disappointment-4d75

I hope they announce a good fix soon https://githubsatellite.com/ otherwise we will have to think about disabling those workflow, but this is a last resort.

You mind if I close this issue?

**Comment by jamescrowley** [comment]
@derberg That does seem like a significant flaw! I'm presuming they are tripping over the same issues on normal CI that you don't usually want to expose secrets to untrusted forks. I'll close the issue :)
