### ISSUE TITLE
Markdown styling for several commonMarks missing

### ISSUE THREAD

**Issue by dweber019** [asyncapi/html-template#162]
#### Describe the bug
The HTML is produced correctly but the styling if broken for the following type:
- Bold
- Blockquote
- Lists (numeric and disc) should be fixed with https://github.com/asyncapi/html-template/issues/142
- Code (inline and block) barely recognizable
- Tables not styled (nice to have)

This happens on all fields, which are commonMark enabled by your documentation.

#### How to Reproduce
https://playground.asyncapi.io/?load=https://gist.githubusercontent.com/dweber019/94f91f07dbc71bc689786e2edebfa42f/raw/ab7125db8c74731df6f801d10490d4b9ab9110da/asyncapi-markdown.yaml

#### Expected behavior
At least Bold and Blockquote should be fixed as they are defined well by commonMark. Table and code would be nice.
In addition it would be nice to have some sanitized html to be rendered ;)

**Comment by derberg** [comment]
@dweber019 thanks for the issue. I'm not sure what is wrong with bold for you, for me it shows bold properly. For the list, it is already fixed in the template, just playground needs update, I opened a PR for that.

Now for the rest, we just need someone who would have time to dig into CSS because from the html-template code point of view, all is good. I mean commonMark is used and descriptions are parsed properly, you get proper HTML tags at the end, they are just not styled

**Comment by derberg** [comment]
latest playground with fixed list is deployed

**Comment by dweber019** [comment]
I can confirm the list is fixed. At least for the normal one. The numeric list is now a normal disc list.
I have retested with the like above and this is the [result](https://ibb.co/K7LcN6r) . As you can see the bold part doesn't look bold.

**Comment by dweber019** [comment]
@derberg created a pull request to fix the list regarding numeric and bold font with strong.

**Comment by derberg** [comment]
@dweber019 great, left a comment

**Comment by dweber019** [comment]
Close as this PR will fix the bug https://github.com/asyncapi/html-template/pull/169
