### ISSUE TITLE
BaseHref parameter breaks functionality of anchors

### ISSUE THREAD

**Issue by magicmatatjahu** [asyncapi/html-template#187]
#### Describe the bug

If we pass to template `baseHref` parameter like `/docs` it breaks anchors (like `#operations-{nameOfOperation}`).

#### How to Reproduce

Pass some spec with `baseHref` parameter like `/docs` (relative path not absolute).

#### Expected behavior

Anchors should works with `baseHref` with any input and in any environment.

**Comment by derberg** [comment]
@magicmatatjahu this one is still valid?

**Comment by magicmatatjahu** [comment]
@derberg That as I remember that issue was "noticed" after moving to the React component but problem was also in the previous solution with Nunjucks. I wonder why we have this parameter? Do you remember? I don't know if it's possible to fix `baseHref` as well as to have still anchors, and I don't want to do weird workarounds.

**Comment by derberg** [comment]
@magicmatatjahu it is important feature for use case like with GitHub Pages for example. Look at https://github.com/derberg/test-experiment/blob/master/.github/workflows/main.yml#L30 where I need to specify `baseHref` because my docs are deployed to https://derberg.github.io/test-experiment/ and therefore without `<base href="/test-experiment/">` CSS files would be fetched from `https://derberg.github.io/css/main.css` instead of `https://derberg.github.io/test-experiment/css/main.css`

**Comment by magicmatatjahu** [comment]
@derberg Right, but as I see that problem with `baseHref` is that we have absolute path to the css, not relative `css/...` and it should be `./css/...` and your problem will be resolved. I wonder if people use `baseHref` for another purposes that yours 🤔

**Comment by derberg** [comment]
no, changes in paths will not solve it, at least as far as I remember I tried it, but don't remember details, it was long time ago

I know people use it as this option did not come from me but from the community. Here is initial issue https://github.com/asyncapi/generator/issues/205

**Comment by derberg** [comment]
still a valid bug and issue that needs a solution

**Comment by sarisia** [comment]
https://github.com/asyncapi/html-template/issues/187#issuecomment-1004196900:

> no, changes in paths will not solve it, at least as far as I remember I tried it, but don't remember details, it was long time ago

I ran into the same issue when we deployed the docs to the S3 subdirectory, but setting `baseHref` to `./` solved this.

How about getting rid of `baseHref`, or setting the default value to `./` (since it works for root URL too)?
