### ISSUE TITLE
If / then / else blocks generate incomplete document

### ISSUE THREAD

**Issue by trsh** [asyncapi/html-template#334]
#### Describe the bug
If / then / else blocks generate incomplete document

#### How to Reproduce
Use something like this:
```
"publish": {
                "summary": "Socket backend API",
                "message": {
                    "name": "Create a lobby/room",
                    "x-CreateRoomPayload-key": "CreateRoomPayload",
                    "payload": {
                        "$schema": "http://json-schema.org/draft-07/schema#",
                        "type": "object",
                        "$id": "CreateRoomPayload",
                        "additionalProperties": false,
                        "required": [
                            "type",
                            "maxPlayers"
                        ],
                        "properties": {
                            "type": {
                                "$id": "RoomType",
                                "enum": [
                                    "private",
                                    "public"
                                ],
                                "type": "string",
                                "description": "Room type"
                            },
                            "secret": {
                                "type": "string",
                                "description": "Password for the room (ignored if public)",
                                "example": "lksadlksladlkksadkl"
                            },
                            "maxPlayers": {
                                "type": "integer",
                                "minimum": 2,
                                "description": "Maximum players who can join",
                                "example": 6
                            }
                        },
                        "if": {
                            "properties": {
                                "type": {
                                    "const": "private"
                                }
                            }
                        },
                        "then": {
                            "required": [
                                "secret"
                            ]
                        }
                    }
                }
            }
```

Results:

![hhhhhhhhhhhhhhhh9](https://user-images.githubusercontent.com/3727523/159959496-988071fd-aab0-4b90-9058-e99e097950dd.png)

#### Expected behavior
Something that clearly states, that if type is 'private', secret is required.

**Comment by trsh** [comment]
Another problem, when using `IF`
![rrrrrrrrrrrrrrrr5](https://user-images.githubusercontent.com/3727523/160080008-7819b786-d9bc-4c8f-a1eb-d1f201a3d6c0.png)

**Comment by trsh** [comment]
This report is still valid. If nobody cares about issues for this repo, then why leave a github garbage cleaner on?

**Comment by magicmatatjahu** [comment]
> If nobody cares about issues for this repo, then why leave a github garbage cleaner on?

To remind about issues that have escaped attention ;)

As far as your problem is concerned this should not be a problem in showing `required`, however, I wonder if there are other JSON Schema keywords that have similar semantic value as `required`.

As for the example on the right, there is nothing we can do about it, because we are using a simple and lightweight library to generate these exemplars and it only generates the simplest examples, without complex looking at the schemas in `if/the/else` etc.

**Comment by trsh** [comment]
> As for the example on the right, there is nothing we can do about it, because we are using a simple and lightweight library to generate these exemplars and it only generates the simplest examples, without complex looking at the schemas in if/the/else etc.

Welp maybe there are better options?

**Comment by magicmatatjahu** [comment]
There are other libraries, but they add a lot of kilobytes to the final bundle (and use nodeJS core libraries), and this is what we want to avoid, which is why we chose https://github.com/Redocly/openapi-sampler. I'm just wondering why your example only generates `type` as it should also generate other fields (but without including if/then/else):

![image](https://user-images.githubusercontent.com/20404945/180731727-dfb4db9f-5b10-46d1-8da5-5f14e8a764e9.png)
