### ISSUE TITLE
Everything breaks after upgrading to version 1.0.0

### ISSUE THREAD

**Issue by albertodiazdorado** [asyncapi/html-template#456]
#### Describe the bug
```sh
yarn upgrade @asyncapi/html-template@0.28.4
yarn build # works
yarn serve # works

yarn upgrade @asyncapi/html-template@latest
yarn add react@^17.0.2 # peer dependency
yarn build # works?
yarn serve # blank page
```

I _think_ that the problem is that the generated `index.html` looks like this (notice `shema = undefined`):
```html
    <body>
      <div id="root"></div>
  
      <script src="js/asyncapi-ui.min.js" type="application/javascript"></script>
  
      <script>
        const schema = undefined;
        const config = {"show":{"sidebar":true},"sidebar":{"showOperations":"byDefault"}};
        AsyncApiStandalone.hydrate({ schema, config }, document.getElementById("root"));
      </script>
    </body>
```

I use the generator like this:
```js
import Generator from "@asyncapi/generator"; // Version 1.14.1

const main = async () => {
  const generator = new Generator(
    "@asyncapi/html-template",
    path.resolve(process.cwd(), `./dist`),
  );
  const yamlFile = await fsPromises.readFile(
    path.resolve(__dirname, "./api-config.yaml"),
    "utf-8",
  );
  await generator.generate(yamlFile);
};

main();
```

Do you have any idea on how to fix? Or how to migrate from version `0.x` to `1.x`? I could not find any migration guide.

**Comment by Traderjoe95** [comment]
I am experiencing the same issue when calling the generator through the `asyncapi` CLI

**Comment by henhal** [comment]
Same here. This was my first ever use of asyncapi, and it took me some time to realize that my HTML being blank wasn't due to me being an idiot. Even rendering the hello world sample resulted in a blank page.

I guess I had bad luck, getting my first impression of this tool from a completely broken version. 🤷 
Works fine when I use `@0.28.4`.

**Comment by zschumacher** [comment]
Same for me, had to pin to 0.28.4

**Comment by jonaslagoni** [comment]
Can you folks provide the AsyncAPI document (or a way for us to reproduce it) that fails to be generated to html?

**Comment by zschumacher** [comment]
I cannot because it is proprietary but I can try to give some more info.

- async api version -> 2.6.0
- command to install cli -> `npm install -g @asyncapi/cli`
- command to generate html -> `asyncapi generate fromTemplate async-api.yml @asyncapi/html-template -o async_api_docs --force-write -p singleFile=true`
- my spec includes info, channels, channels/subscribe, channels/parameters, components, components/schemas, components/messages

**Comment by henhal** [comment]
@jonaslagoni I provided one in the linked issue - but even your own hello world from the docs can reproduce the issue. It's _any_ document as far as I see.

**Comment by jonaslagoni** [comment]
What version of the CLI/generator do you folks use? 

With CLI `0.60.1` and even `0.59.0` with the following AsyncAPI document: https://github.com/asyncapi/html-template/blob/master/test/spec/asyncapi_v2.yml It correctly generates the docs for me.

<img width="1753" alt="image" src="https://github.com/asyncapi/html-template/assets/13396189/dc11b825-f8a0-46d5-8a4d-37f3ca0880e0">

**Comment by smoya** [comment]
I created a new repository that confirms something doesn't work as expected. 

https://github.com/smoya/asyncapi-test-generation

Just clone the repo, run `npm i && npm run start` and you will have the output of both template versions in `out/1.0.0` and `out/0.28.4`. 
I confirm that opening the `out/1.0.0/index.html` shows a blank page. However the one from `out/0.28.4` shows the documentation.

**Comment by Traderjoe95** [comment]
AsyncAPI CLI 0.60.0 on Node 21.1.0/Windows

```
> asyncapi --help
All in one CLI for all AsyncAPI tools

VERSION
  @asyncapi/cli/0.60.0 win32-x64 node-v21.1.0

USAGE
  $ asyncapi [COMMAND]

TOPICS
  config    CLI config settings
  generate  Generate models and template
  new       Creates a new asyncapi file
  start     Start asyncapi studio

COMMANDS
  bundle    bundle one or multiple asyncapi documents and their references together.
  config    CLI config settings
  convert   Convert asyncapi documents older to newer versions
  diff      Find diff between two asyncapi files
  generate  Generate typed models or other things like clients, applications or docs using AsyncAPI Generator templates.  new       Creates a new asyncapi file
  optimize  optimize asyncapi specification file
  start     Start asyncapi studio
  validate  validate asyncapi file
```

It generates an empty page for me with https://github.com/asyncapi/html-template/blob/master/test/spec/asyncapi_v2.yml. The problem remains after updating to 0.60.1.

**Comment by derberg** [comment]
@jonaslagoni when you run generation (you are the only one where it works) can you do it with `debug` flag, it will clarify what html template version you're using in generation process

**Comment by hntirgeam** [comment]
Same behavior here even on 0.28.4

```
ag <...>.yaml /app/html-template -o <...> --force-write --debug

Remember that your local template must have its own node_modules installed first, "npm install" is not triggered by the generator.
Template sources taken from /app/html-template.
Version of used template is 0.28.4.
[BABEL] Note: The code generator has deoptimised the styling of <...>/asyncapi-ui.min.js as it exceeds the max of 500KB.
File <...>/index.html.js couldn't be found. Error: ENOENT: no such file or directory, stat '<...>/index.html.js'


Done! ✨
Check out your shiny new generated files at <...>
```

And then: 
```
tail -n 7 <...>/index.html
    <script>
      const schema = undefined;
      const config = {"show":{"sidebar":true},"sidebar":{"showOperations":"byDefault"}};
      AsyncApiStandalone.hydrate({ schema, config }, document.getElementById("root"));
    </script>
  </body>
</html>
```
generator version:
```
ag --version
1.14.1
```

**Comment by jonaslagoni** [comment]
Yeah, gonna try to reproduce it on a clean slate.

Pretty sure I know the cause, but why it's the cause I don't understand 😅 Last time this happened during development it was a miss-match between parser versions... 

Gonna see if I can dig up the problem.

**Comment by jonaslagoni** [comment]
So yeah, this was a multitude of bugs... But the TL;DR; is that it's a parser dependency mismatch that caused it, more specifically after https://github.com/asyncapi/parser-js/pull/892 was introduced the dependencies and implementation started to drift across implementations because it was a breaking change and was introduced on a pre-release branch meaning all dependant libraries started using it...

I could hot-fix it here as well, but does not make much sense to introduce as each fix elsewhere will break it again... Here is the list of PRs that need to be merged before it is fully fixed:
- https://github.com/asyncapi/parser-js/pull/902
- https://github.com/smoya/multi-parser-js/pull/5
- https://github.com/asyncapi/generator/pull/1066
- https://github.com/asyncapi/html-template/pull/459


Sorry for the inconvenience folks... 🙃

**Comment by derberg** [comment]
Can anyone confirm if issue is still there?

From @jonaslagoni list of issues I see all are merged

**Comment by albertodiazdorado** [comment]
@derberg works like a charm, I can confirm. I am closing this issue :D

**Comment by albertodiazdorado** [comment]
Thanks @jonaslagoni

**Comment by nilkanth987** [comment]
@jonaslagoni , This is still happing for me. 
Here is my configs
```
node: 17.8.0
"@asyncapi/generator": "^1.17.4",
"@asyncapi/html-template": "^2.1.5",
```

<img width="1215" alt="Screenshot 2024-02-02 at 3 48 34 PM" src="https://github.com/asyncapi/html-template/assets/12413581/84759710-2bf0-4a56-8b2d-67d490c14353">

Can anyone tell me how to fix it?
