### ISSUE TITLE
Examples should be in a message instead of payload by async-api 2.0.0 specifications

### ISSUE THREAD

**Issue by GordeevArt** [asyncapi/html-template#59]
Examples should be in a message instead of payload by async-api 2.0.0 specifications

https://www.asyncapi.com/docs/specifications/2.0.0/#messageObjectExamples

* Add examples tag with value `- "test": '{"command": "off", "sentAt": "2020-09-10T10:47:22Z"}'` in message into test **asyncapi.yml** file. 
[asyncapi.yml.txt](https://github.com/asyncapi/html-template/files/5200038/asyncapi.yml.txt)
* Run `npm run develop`
* Open generated **index.html** in browser

![image](https://user-images.githubusercontent.com/2003488/92696909-472a2180-f353-11ea-8ed5-b874f56716b0.png)

Expected **{"command": "off", "sentAt": "2020-09-10T10:47:22Z"}** instead of generated example.

**Comment by derberg** [comment]
@GordeevArt thanks so much for reporting it. 

To fix it, `getPayloadExamples` function must be fixed in [here](https://github.com/asyncapi/generator-filters/blob/master/src/customFilters.js#L40). This function must return an example that is later used [here](https://github.com/asyncapi/html-template/blob/master/partials/example.html#L17-L21) in the template.

@fmvilas do you recall why `payload` property is expected in the payload example? or am I reading it wrong? I know `payload` is in [this](https://github.com/asyncapi/asyncapi/issues/329) proposal but it is pretty fresh
```js
  if (Array.isArray(msg.examples()) && msg.examples().find(e => e.payload)) {
    // Instead of flat or flatmap use this.
    return _.flatMap(msg.examples().map(e => e.payload).filter(Boolean));
  }
```

I'm also confused because of https://github.com/asyncapi/asyncapi/pull/436/files. Is it a bug fix for 2.0 or a feature for 3.0. For me, it is a breaking change if now I should not provide names for `examples` and that their type MUST match the type in payload.

**Comment by GordeevArt** [comment]
It works for me if I set example value to `- "payload": {"command": "off", "sentAt": "2020-09-10T10:47:22Z"}`

**Comment by fmvilas** [comment]
@derberg In theory, it's a breaking change but in practice it's actually just a typo. It was never expected to be an array with keys. My fault.

@GordeevArt @derberg Both `message.examples` and `payload.examples` are valid places if you use JSON Schema as the payload format. We probably should check for the existence of both and give priority to `message.examples`.

**Comment by derberg** [comment]
@fmvilas in practice is this change going into https://github.com/asyncapi/asyncapi-node or not?

The function that gets example first checks for the `message.examples` and then `payload.examples`. But it is just "hardcoded" to check example with `payload` key `msg.examples().find(e => e.payload)`, like there was an assumption that you can have `payload` example and maybe `header` example too. I propose to get rid of it and get all examples, no matter what is the key name

**Comment by fmvilas** [comment]
I messed it up here. The real intention behind `examples` at Message Object is to contain an array of objects with `headers` and/or `payload` keys. Their values can be anything though but they must match the definition.

So, a valid example should look like the following:

```yaml
examples:
  - headers:
      myHeader: 1
    payload:
      payloadKey1: hello
      payloadKey2: bye
  - headers:
      myHeader: 2
    payload:
      payloadKey1: hello2
      payloadKey2: bye2
```

The reason is that we want to have an example of both, headers and/or payloads.

**Comment by gutee** [comment]
@fmvilas I see you have reverted #436 and we don't fully understand your last comment in this thread. With the last example you provide it seems the type matches, but the functionality behind the headers/payload example in each array item is completely new, which looks like it shouldn't be added in the 2.0.0 specification.

If you keep the previous type (reverting #436), we would need to know what to interpret from the type that is currently in the specification.

Also, if headers and payload will validate two different and isolated facets, why would they be grouped in array items? does it have a meaning? It seems the best approach would be to separate it into two different example facets.

**Comment by fmvilas** [comment]
Yeah, the reason is that in some cases you want to show header/payload pairs, that's why they're grouped together. For instance, as a way to communicate something like "these headers make sense with this payload". Does it make sense?

**Comment by gutee** [comment]
@fmvilas It makes sense, the thing is this is not in the specification at all, so we don't know how to interpret the 2.0.0 version, as we validate examples in the APIs. If this will work this way, and be restricted only to `payload` and `headers` with that specific notation, it should be in the specification. We need to know how this works and how this will validate. As for 2.0.0 version we should come up with what to do there, as this is a major change in the behaviour.

**Comment by fmvilas** [comment]
I understand but it's not a breaking change in the behavior but was rather a lack of clarity. If you look at [the spec on v2.0.0 tag](https://github.com/asyncapi/asyncapi/blob/2.0.0/versions/2.0.0/asyncapi.md#messageObjectExamples) it says:

> Type: [Map[string, any]]
> Description: An array with examples of valid message objects.

It's an array of examples of valid Message objects. From the data point of view, only headers and payload can be provided as examples, that's the reason only `headers` and `payload` can be in the Map of `string` to `any`.

**Comment by gutee** [comment]
@fmvilas I don't think anyone can know that they need to use those two keywords in their specification from what is written in the 2.0.0 tag. The type is correct, but the behaviour is not at all defined. Also, the type only applies to the `payload` facet inside the `examples` facet, as the `headers` facet has one more level for the name of each header. The `examples` facet also is now a closed shape, where before it was open.

I think it's not only a lack of clarity, as the behaviour and validations are not defined at all.

**Comment by fmvilas** [comment]
You're right. Being 100% consequents with what's written there it would be a breaking change, however, I think we should be pragmatics here and not bump a major version just because of this change. The intention since the beginning was to have this closed shape and tooling does reflect that. It's one of these unlucky situations. We'll be more careful with the next version.

**Comment by gutee** [comment]
@fmvilas No problem, can you reflect the change in the specification please? So that we know that it will not change behaviour in the last minute.

**Comment by fmvilas** [comment]
Absolutely. I just created this PR to clarify the definition: https://github.com/asyncapi/asyncapi/pull/453.

**Comment by gutee** [comment]
Great, thanks @fmvilas, I think that's more clear now.

**Comment by derberg** [comment]
@GordeevArt I'm guessing we can close this one?

**Comment by GordeevArt** [comment]
Yep. Thanks!
