### ISSUE TITLE
Creating Templates with Single File Parameter causes Error

### ISSUE THREAD

**Issue by oanguin** [asyncapi/html-template#78]
#### Describe the bug
When using the single file parameter an error is thrown.

#### How to Reproduce
```{bash}
ag "schemas/school-events.yaml" @asyncapi/html-template --output "docs/school-events/" -p singleFile=true --force-write
```
```{bash}
Something went wrong:
TypeError [ERR_INVALID_CALLBACK]: Callback must be a function. Received { recursive: true }
    at makeCallback (fs.js:133:11)
    at Object.rmdir (fs.js:675:14)
    at generate:after (/usr/local/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/html-template/hooks/01_removeNotRelevantParts.js:21:16)
    at /usr/local/lib/node_modules/@asyncapi/generator/lib/generator.js:756:20
    at Array.map (<anonymous>)
    at Generator.launchHook (/usr/local/lib/node_modules/@asyncapi/generator/lib/generator.js:754:43)
    at Generator.generate (/usr/local/lib/node_modules/@asyncapi/generator/lib/generator.js:188:16)
    at async /usr/local/lib/node_modules/@asyncapi/generator/cli.js:123:9
```
### Version Used
- npm@6.14.8
- node@12.2.0
- asyncapi/generator@v1.0.0-rc.11

#### Expected behavior
The templates are generated correctly.

**Comment by derberg** [comment]
This is strange. The issue is related to [this](https://github.com/asyncapi/html-template/blob/master/hooks/01_removeNotRelevantParts.js#L21) but from the docs looks like it is used properly but this is still an [experimental function](https://nodejs.org/api/fs.html#fs_fs_rmdir_path_options_callback). When I was testing I was on Node.js 12.18.3 and all was fine. Maybe they are breaking experimental features more often 🤔 try upgrading to 12.18 and let us know how it works. We will most probably have to replace current logic with something stable.

**Comment by oanguin** [comment]
> This is strange. The issue is related to [this](https://github.com/asyncapi/html-template/blob/master/hooks/01_removeNotRelevantParts.js#L21) but from the docs looks like it is used properly but this is still an [experimental function](https://nodejs.org/api/fs.html#fs_fs_rmdir_path_options_callback). When I was testing I was on Node.js 12.18.3 and all was fine. Maybe they are breaking experimental features more often 🤔 try upgrading to 12.18 and let us know how it works. We will most probably have to replace current logic with something stable.

The bug does not occur in version `12.18` of Node as mentioned by @derberg .

**Comment by derberg** [comment]
video about how to solve the issue https://youtu.be/Iqs_2BiNEEo?t=1110
